
styleguide: plataformatec/linters

engines:
  credo:
    enabled: true
  fixme:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  shellcheck:
    enabled: true
  remark-lint:
    enabled: true

exclude_paths:
- config
- test
- webapp/*.js
- webapp/config
- webapp/src/assets
