#!/bin/bash

# Angular stuff
rm -fR priv/static/*
pushd webapp
npm install
ng build --aot --target=production
popd

# Elixir Stuff
rm -fR _build
mix deps.get --only prod
export REBAR_DEPS_DIR=`pwd`/deps
MIX_ENV=prod mix do compile, release
