#!/bin/bash

# Angular stuff
rm -fR priv/static/*
pushd webapp
npm install
ng build --aot --target=production
popd

# Elixir Stuff
mix deps.get --only prod
MIX_ENV=prod mix do release.clean, compile, release
